### ISSUE TITLE
Improvement code for Kubernetes 

### ISSUE THREAD

**Issue by ionutz89** [fmdlc/ISP-Checker#29]
Hello,

You should remove this line ```clusterIP: 10.43.37.100``` from your ISP-Checker-deploy.yaml

Not everyone is using the same network address. 

Also, you can add ingress and service for grafana like:

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: isp-checker
spec:
  type: ClusterIP
  ports:
    - name: grafana
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: isp-checker
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: grafana.com
      http:
        paths:
          - backend:
              service:
                name: grafana
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
      - grafana.com
      secretName: grafana-cert
```

**Comment by villasenor** [comment]
Agreed, not everyone has the same IP range in their cluster so that line for the `influxdb-svc` should be removed. Yes, and a `LoadBalancer` block should be added as well (can be commented out by default until you get Helm going):
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    app.kubernetes.io/app: grafana
    app.kubernetes.io/project: isp-checker
  name: grafana-svc
  namespace: monitoring
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
```
